function config = generate_config()
    %GENERATE_CONFIG Returns the configuration structure for the extended hankel HAVOK pipeline
    %
    % OUTPUT:
    %   config - Structure containing all configuration parameters

    %% Output File Configuration
    config.output_filename = 'havok_modular_results.h5';

    %% General Configuration
    config.num_workers = 4;  % Number of CPUs to use for parallel processing
    config.error_mode = 'fail_fast';  % Error handling mode: 'resilient' or 'fail_fast'
    
    % Logging Configuration
    config.logging = struct();
    config.logging.console_level = 'info';
    config.logging.file_level = 'debug';
    config.logging.filepath = 'logs/havok_modular.log';
    
    %% Data Pipeline Parameters
    
    % Global Simulation Parameters
    config.params.globals = struct( ...
        'dt', 0.001, ...                         % Time step for high fidelity simulation
        'master_timeseries_length', 1000, ...    % Total simulation time for master series
        'lambda', 0 ...                          % Sparsification parameter for regression
    );

    % Parameter Grid for Comprehensive Sweep
    config.params.grid = struct();
    config.params.grid.timeseries_length = [30, 50]; % Time series lengths to test (in time units)
    config.params.grid.index_delay = int32([1, 5]); % Index delay parameters for time-delay embedding
    config.params.grid.variable_combination = {'x', 'xz'}; % Variable combinations to test from Lorenz system [x, y, z] % Options: 'x', 'y', 'z', 'xy', 'xz', 'yz', 'xyz'
    config.params.grid.embedding_dim_multiple = int32([30, 50]); % Embedding dimension multiples (number of time-delayed copies to stack)
    config.params.grid.hankel_type = {...
        'normal', ...           % Standard extended Hankel matrix
        'vertical', ...         % Vertical polynomial extension
        'horizontal', ...       % Horizontal polynomial extension  
        'block_vertical'...     % Block vertical extension
    };
    config.params.grid.hankel_max_degree = int32([2, 3]); % Maximum polynomial degrees for extended Hankel matrices
    config.params.grid.hankel_max_harmonics = int32([0, 1]); % Maximum harmonics for polynomial extensions
    config.params.grid.truncation_rank = int32([10, 15]); % Truncation ranks for SVD (number of modes to retain)
    config.params.grid.library_max_degree = int32([1]); % Maximum polynomial degrees for regression library
    config.params.grid.library_max_harmonics = int32([0]); % Maximum harmonics for regression library

    % Filtering parameter runs
    config.params.filter = @(p, G) p.truncation_rank < p.embedding_dim_multiple;
    
    %% Stages Configuration
    config.stages = struct();

    % Stage 1: Master Timeseries Generation
    config.stages.compute_master_timeseries = struct(...
        'function', @compute_master_timeseries, ...
        'params', {'master_timeseries_length', 'dt'}, ...
        'inputs', struct(), ... % No inputs
        'outputs', { ...
            struct('name', 'master_timeseries', 'storage_policy', 'memory_only'), ...
            struct('name', 'time_vector', 'storage_policy', 'memory_only') ...
        }, ...
        'execution_mode', 'global' ...
    );

    % Stage 2: Hankel Matrix Computation
    config.stages.compute_hankel = struct(...
        'function', @compute_hankel, ...
        'params', {'timeseries_length', 'index_delay', 'variable_combination', 'embedding_dim_multiple', 'hankel_type', 'hankel_max_degree', 'hankel_max_harmonics'}, ...
        'inputs', struct(...
            'timeseries', 'compute_master_timeseries.master_timeseries', ...
            'time_vec',   'compute_master_timeseries.time_vector' ...
        ), ...
        'outputs', {struct('name', 'H', 'storage_policy', 'memory_only')}, ...
        'execution_mode', 'per_run' ...
    );

    % Stage 3: Singular Value Decomposition (SVD)
    config.stages.compute_svd = struct(...
        'function', @compute_svd, ...
        'params', {'truncation_rank'}, ...
        'inputs', struct('H', 'compute_hankel.H'), ...
        'outputs', { ...
            struct('name', 'U', 'storage_policy', 'memory_only'), ...
            struct('name', 'S', 'storage_policy', 'memory_only'), ...
            struct('name', 'V', 'storage_policy', 'memory_only'), ...
            struct('name', 'singular_values', ...
                'storage_policy', 'memory_only' ... % @(p, G) p.truncation_rank == max(G.truncation_rank) ...
            ) ...
        }, ...
        'execution_mode', 'per_run' ...
    );

    % Stage 4: Numerical Derivative Calculation
    config.stages.compute_numerical_derivative = struct(...
        'function', @compute_numerical_derivative, ...
        'params', {'dt'}, ...
        'inputs', struct('V', 'compute_svd.V'), ...
        'outputs', {struct('name', 'dVdt', 'storage_policy', 'memory_only')}, ...
        'execution_mode', 'per_run' ...
    );

    % Stage 5: Regression Library Construction
    config.stages.construct_regression_library = struct(...
        'function', @construct_regression_library, ...
        'params', {'library_max_degree', 'library_max_harmonics', 'truncation_rank'}, ...
        'inputs', struct('V', 'compute_svd.V'), ...
        'outputs', {struct('name', 'Theta', 'storage_policy', 'memory_only')}, ...
        'execution_mode', 'per_run' ...
    );

    % Stage 6: Sparse Regression
    config.stages.perform_sparse_regression = struct(...
        'function', @perform_sparse_regression, ...
        'params', {'lambda'}, ...
        'inputs', struct(...
            'Theta', 'construct_regression_library.Theta', ...
            'dVdt', 'compute_numerical_derivative.dVdt' ...
        ), ...
        'outputs', { ...
            struct('name', 'Xi', 'storage_policy', 'persistent'), ...
            struct('name', 'A', 'storage_policy', 'persistent'), ...
            struct('name', 'B', 'storage_policy', 'persistent') ...
        }, ...
        'execution_mode', 'per_run' ...
    );

    % Stage 7: Model Assembly and Reconstruction
    config.stages.reconstruction.function = @compute_reconstruction;
    config.stages.reconstruction.params = {'dt', 'truncation_rank'};
    config.stages.reconstruction.inputs = struct( ...
        'Xi', 'perform_sparse_regression.Xi', ...
        'A',  'perform_sparse_regression.A', ...
        'B',  'perform_sparse_regression.B', ...
        'U',  'compute_svd.U', ...
        'S',  'compute_svd.S', ...
        'V',  'compute_svd.V' ...
    );
    config.stages.reconstruction.outputs = { ...
        struct('name', 'y', 'storage_policy', 'memory_only'), ...
        struct('name', 't_recon', 'storage_policy', 'memory_only'), ...
        struct('name', 'model_eigenvalues', 'storage_policy', 'memory_only'), ...
        struct('name', 'forcing_term', 'storage_policy', 'memory_only') ...
    };
    config.stages.reconstruction.execution_mode = 'per_run';

end